include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = EchoServ
EchoServ_OBJC_FILES = main.m EchoServ.m

EchoServ_TOOL_LIBS = -lnetclasses

ADDITIONAL_OBJCFLAGS = -Wall

include $(GNUSTEP_MAKEFILES)/tool.make

