include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = IRCBot
IRCBot_OBJC_FILES = main.m NetBase.m NetTCP.m IRCObject.m LineObject.m IRCBot.m 

ADDITIONAL_OBJCFLAGS = -Wall

include $(GNUSTEP_MAKEFILES)/tool.make

