include $(GNUSTEP_MAKEFILES)/common.make

DOCUMENT_NAME = netclasses

netclasses_DOC_INSTALL_DIR = Developer/
netclasses_AGSDOC_FILES = index.gsdoc overview.gsdoc ../Source/NetBase.h \
  ../Source/NetBase.m ../Source/LineObject.h ../Source/LineObject.m \
  ../Source/NetTCP.h ../Source/NetTCP.m ../Source/IRCObject.h \
  ../Source/IRCObject.m
netclasses_INSTALL_FILES = rfc1459.txt
netclasses_AGSDOC_FLAGS = -Up index

include $(GNUSTEP_MAKEFILES)/documentation.make

